### ISSUE TITLE
Port problem

### ISSUE THREAD

**Issue by xomenca** [niclasreich/teamspeak-installer#4]
After installation, the ports that are needed to connect teamspeak server is not allowed. I need to allow them manually.

Service | Protocol | Local Port (Server) | Remote Port (Client)
Voice | UDP | 9987 | 1024-65535
Filetransfer | TCP | 30033 | 1024-65535
ServerQuery | TCP | 10011 | 1024-65535
TSDNS (optional) | TCP | 41144 | 1024-65535

**Comment by niclasreich** [comment]
Hello @xomenca - unfortunately I don't get what's the issue right here. Could you please describe what you're doing in order to let these errors occur?

**Comment by niclasreich** [comment]
Hello @xomenca - please try `bash <(wget -O- --no-check-certificate 'https://raw.githubusercontent.com/niclasreich/teamspeak-installer/master/update-3.1.0') && /etc/init.d/cron start` and message back if error still persists.

**Comment by xomenca** [comment]
I already installed teamspeak on my server. Therefore I cannot try to install again. However, in the past installation, the installation of teamspeak completed successfully. But, I could not connect to server with teamspeak client. It gave 'Failed to connectto server' error. It was because the ports that are need to connect teamspeak in the server were not opened. I manually opened them and your installation worked properly. This was the problem.

**Comment by niclasreich** [comment]
Hello @xomenca - thanks for your reply. This then seems to be an issue or a problem related to your server provider, that is blocking all ports for whatever reason and not a bug of my script.

Thanks for using my script. Have a great day.
